### ISSUE TITLE
Mon premier service en Rust

### ISSUE THREAD

**Issue by fteychene** [Rust-Toulouse/CFP#2]
{ Please fill in this template to help us have a better understanding of your talk}

Language of the talk: 
- [x] 🇫🇷
- [ ] 🇬🇧

Please use the language you will use during the presentation to fill in this form.

## About you

* Name: Francois Teychene
* Link to profile picture: https://pbs.twimg.com/profile_images/865274992845631488/TnQRrKX7_400x400.jpg
* Twitter handle: fteychene
* Experience as a speaker:
    - [ ] beginner
    - [x] advanced
    - [ ] expert
* Links to your previous events, videos etc. : 

 - Mon premier service en Rust : https://www.youtube.com/watch?v=XO55cz7fg-g  - BDX I/O
 - Au secourd ma prod est sous Docker : https://www.youtube.com/watch?v=8oDjCvFrwgU - DevFest Toulouse 2016, Devoxx 2017, MixIt 2017, RivieraDev 2017  
 - Un PaaS pour votre équipe en 20 min : https://www.youtube.com/watch?v=T_-PUZQr_yg - DevFest Nantes 2016   
 - Architecture migroservice - JugSummerCamp 2017, Codeurs en Seine 2018
 - L'UX a sauvé mon DevOps : https://www.youtube.com/watch?v=Axy_VTzg2XY - DevFestToulouse 2017, Devops DDay 2017, DevFest Nantes 2017, RivieraDev 2018, DevFest Lilles 2018 , Devops Rex 2018
 - SystemD, de /dev/null à root - DevFest Toulouse 2018
 - Devops ? C'est comme Scrum mais avec Docker ... - Devoxx Maroc 2018
---

## Description of your talk
Vous avez surement entendu parlé de Rust, ce langage qui est à la mode mais qui ne semble pas vous concerner.  
Parce que bon, un langage sans VM, ultra performant, c'est sympa, mais c'est difficile de voir comment l'utiliser pour des besoins "standards". Et à chaque fois on présente comment faire des outil en CLI ou comment la mémoire est efficacement gérée ...  
Bref on a l'impression que c'est un langage réservé aux ingénieurs systèmes et on le compare à du C.

Et si je vous disais que l'on peut faire des webservices en Rust, de manière simple et élégante et que l'on garde tout les avantages classique du langage (performance, safety, ...) ? C'est ce que je vous propose de découvrir dans cette session.

---

## Miscellaneous

* Talk level :
    - [x] beginner
    - [ ] advanced
    - [ ] expert
* Length (max 45 min) : 45min
* Format:
    - [x] Slides
    - [x] Live coding
* Availability: From January 2019

**Comment by d-plaindoux** [comment]
Done done 🤗
