### ISSUE TITLE
La vie en Rust

### ISSUE THREAD

**Issue by magnet** [Rust-Toulouse/CFP#3]
Language of the talk: 
- [x] French
- [x] English if people want

## About you

* Name: Simon Chemouil
* Link to profile picture: 
* Twitter handle: @simach
* Experience as a speaker:
    - [ ] beginner
    - [x] intermediate
    - [ ] expert
* Links to your previous events, videos etc. : Hmm

---

## Description of your talk

**La vie en Rust**  

Faut-il se mettre à Rust ? La même question se pose à chaque fois qu'un langage atteint la masse critique qui permet à son nom de parvenir jusqu'à nos oreilles... mais il est difficile de déterminer si le jeu en vaut la chandelle. 

Combien de temps faut-il pour devenir productif en Rust ? Ce fameux "borrow checker" qui, d'une certaine façon, remplace le garbage collector est-il difficile à prendre en main ?

On le sait, Rust produit du code performant, mais ce code est-il lisible, maintenable et facilement réutilisable ? Où se situe Rust en terme d'abstraction comparé à Java, C#, Python, Scala ou Haskell... que fait-il mieux, et moins bien ? Ce faisant, quels types de projets profitent-ils des qualités Rust ? 

Enfin, que vaut l'écosystème : les bibliothèques open source, l'outillage, et la communauté ? Quels degrés de maturité ?

Voilà les questions auxquelles Simon tentera de répondre, à travers son expérience récente et des exemples concrets de code issu de ses projets.

---

## Miscellaneous

* Talk level :
    - [X] beginner
    - [ ] advanced
    - [ ] expert
* Length (max 45 min) : 30-45mins 
* Format:
    - [x] Slides
    - [x] Live coding
* Availability: TBD

**Comment by d-plaindoux** [comment]
30-45 minutes uniquement avec autant de thèmes ?

**Comment by magnet** [comment]
Mon but dans ce talk n'est pas de présenter les fonctionnalités en détail mais le "feeling", les options que Rust propose (à gros grain), et sur des exemples précis et relativement peu nombreux (4-5)
Ca sera sans doute plutôt 45 minutes que 30, mais je veux faire aussi succinct que possible autant pour le public que pour moi. 
D'un point de vue présentation du langage, ça sera donc superficiel ; mais j'essaierai de restituer l’intérêt de Rust de façon synthétique.
