### ISSUE TITLE
Rust et WebAssembly 

### ISSUE THREAD

**Issue by ogadaki** [Rust-Toulouse/CFP#5]
Language of the talk: 
- [x] 🇫🇷
- [ ] 🇬🇧

## About you

* Name: Nicolas Decoster
* Link to profile picture: https://2017.devfesttoulouse.fr/images/speakers/nicolas-decoster.jpg
* Twitter handle: [@nnodot](https://twitter.com/nnodot)
* Experience as a speaker:
    - [ ] beginner
    - [x] advanced
    - [ ] expert
* Links to your previous events, videos etc.
Talk sur WebAssembly lors du DevFest Toulouse 2017 : https://www.youtube.com/watch?v=6nNTQOMb3H8
---

## Description of your talk

Une petite conférence pour essayer de cerner ce qu'est cet OVNI dans l'univers des technos web. Ce nouveau standard vient de débarquer dans les navigateurs et soulève pas mal de questions sur ses promesses (rapidité ! cible de compilation universelle !) et sur ses cas d’utilisations concrets.

Lors de cette conférence je commencerai par un peu d'histoire et de technique pour s'éclaircir les idées et pour voir comment on travaille avec cette techno dans l'écosystème Rust. Nous verrons comment produire du WebAssembly à partir de code Rust et comment cela s'intègre et s'utilise côté navigateur.

---

## Miscellaneous

* Talk level :
    - [x] beginner
    - [ ] advanced
    - [ ] expert
* Length (max 45 min) :  45 min
* Format:
    - [x] Slides
    - [ ] Live coding
* Availability: après fin février

**Comment by magnet** [comment]
Soirée du 28 mars 2019! Merci Nicolas :)
